[package]
name = "cargo-dev-install"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-dev-install"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
cargo_metadata = "0.19"
